routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
//

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//



Route::group(['middleware' => 'auth'], function(){

  Route::group(['middleware' => 'check_ban'], function(){
          // for users
        Route::get('/', 'App\Http\Controllers\TransactionController@transaction_history')->name("home");
        Route::get('/transaction/history', 'App\Http\Controllers\TransactionController@transaction_history')->name("transaction_history");
        Route::get('/transfer/create', 'App\Http\Controllers\TransactionController@transfer_create')->name("transfer_create");
        Route::get('/transfer/copy/{transaction_id}', 'App\Http\Controllers\TransactionController@transfer_copy')->name("transfer_copy");
        Route::post('/transfer/transfering', 'App\Http\Controllers\TransactionController@transfering')->name("transfering");
        Route::get('/transfer/result', 'App\Http\Controllers\TransactionController@transfer_result')->name("transfer_result");
        Route::get('/catalog/user-list', 'App\Http\Controllers\CatalogController@user_list')->name("user_list");
   });

  //admin control panel
  Route::group(['prefix' => 'admin'], function(){

        Route::group(['middleware' => 'can:isAdmin'], function(){
        //admin access
        Route::resource('user', 'App\Http\Controllers\AdminControllers\UserController');
        Route::resource('transaction', 'App\Http\Controllers\AdminControllers\TransactionController');

      });
  });
});


require __DIR__.'/auth.php';

app/Http/Controllers/AdminControllers/TransactionController.php
<?php

namespace App\Http\Controllers\AdminControllers;

use App\Http\Controllers\Controller;
use App\Models\Transaction;
use Illuminate\Http\Request;

use App\Helpers\Filters\TransactionAdminFilter;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $rows = TransactionAdminFilter::get_rows($request);
        return view('admin_views.transaction.index', compact(
          'rows',
          'request'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::where(["id" => $id])->with(["user_rel", "operation_user_rel"])->firstOrFail();
        return view('admin_views.transaction.details', ['transaction' => $transaction]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $transaction = Transaction::where(["id" => $id])->with(["user_rel", "operation_user_rel"])->firstOrFail();
        return view('admin_views.transaction.edit', ["transaction" => $transaction]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $request->validate([
          'amount'=> ['required', 'min:0.01', 'max:1000000', "regex:/^\d+(.\d{1,2})?$/"],
          'fail_message'=>'string|max:100',
        ]);

       $transaction->amount =  $request->get('amount');
       $transaction->fail_message = $request->get('fail_message');
       $transaction->save();
       return redirect()->route('transaction.index', [])->with('message', 'Transaction updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \Validator;
use Illuminate\Support\Facades\Auth;
use Redirect;

use App\Helpers\Filters\TransactionFilter;
use App\Http\Requests\CreateTransferRequest;
use App\Rules\CheckExistTransactionByUser;
use App\Models\Transaction;
use App\Models\User;
use App\Helpers\TransferOperation\TransferHandler;
use App\Helpers\TransferOperation\TransferTransaction;

class TransactionController extends Controller
{

    public function transaction_history(Request $request)
    {
        $rows = TransactionFilter::get_rows($request);

        return view('transaction.transaction_history', compact(
          'rows',
          'request'
        ));
    }


    public function transfer_create(Request $request)
    {
        $request_uid = Transaction::generate_request_uid();
        return view('transaction.transfer_create', compact(
          'request',
          "request_uid",
        ));
    }

    public function transfer_copy(Request $request, $transaction_id)
    {
        $user = Auth::user();


        //$transaction_id = $request->input('transaction_id');
        $transaction = Transaction::where(["id" => $transaction_id, "user_id" => $user->id  , "operation_type" => "debiting"])->with(["operation_user_rel"])->firstOrFail();

        return Redirect::route('transfer_create')->withInput(["operation_user" => $transaction->operation_user_rel->name, "operation_user_id" =>$transaction->operation_user, "transfer_amount" => $transaction->amount ]);

    }



    public function transfering(CreateTransferRequest $request)
    {

      $user = Auth::user();
      $operation_user = User::find($request->get("operation_user_id"));
      $amount =  $request->get("transfer_amount");
      $request_uid =  $request->get("request_uid");

      $transaction_operation = new TransferTransaction();
      $transfer = new TransferHandler($transaction_operation);
      $sender_transaction = $transfer->transfer($user, $operation_user, $amount, $request_uid);

      return redirect()->route('transfer_result', ['transaction_id' =>  $sender_transaction->id]);

    }


    public function transfer_result(Request $request)
    {
        $validator =  Validator::make($request->all(), [ 'transaction_id' => ['required', 'integer',  new  CheckExistTransactionByUser] ]);

        if($validator->fails()){
            return response('Transaction not found', 400);
        }

        $user_id = Auth::id();
        $transaction = Transaction::with('operation_user_rel')->where("id", $request->transaction_id)->where('user_id', $user_id)->first();


        return view('transaction.transfer_result', compact(
          "transaction"
        ));



    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin_views/transaction/_transaction_table.blade.php
{{ $rows->links() }}
<br>
<hr>
<br>

{{ Form::open(array('url' => route('transaction.index') ,  'method' => 'get')) }}

  <table class="w-full text-left rounded-lg">
      <thead>
          <tr class="text-gray-800 border border-b-0">
              <th class="px-4 py-3">ID</th>
              <th class="px-4 py-3">Date</th>
              <th class="px-4 py-3">Result transaction</th>
              <th class="px-4 py-3">Amount</th>
              <th class="px-4 py-3">Balance after operation</th>
              <th class="px-4 py-3">User</th>
              <th class="px-4 py-3">Operation</th>
              <th class="px-4 py-3">User Operation</th>
              <th class="px-4 py-3">Actions</th>
          </tr>
      </thead>
      <thead>
          <tr class="text-gray-800 border border-b-0">
              <th class="px-4 py-3"></th>
              <th class="px-4 py-3">
                {{ Form::date('created_at', $request->input('created_at') , array('class' => 'form-control' ,'onchange'=>'this.form.submit()'  )) }}

                @if ($request->input('sort_by') == '-created_at' )
                  <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
                  <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'created_at']) }}"> &uarr; </a>
                @elseif($request->input('sort_by') == 'created_at' )
                  <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-created_at']) }}"> &darr;</a>
                  <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
                @else
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-created_at']) }}"> &darr;</a>
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'created_at']) }}"> &uarr; </a>
                @endif
               </th>


              <th class="px-4 py-3">
                <select class="form-control" name="is_success" class="form-control" onchange="this.form.submit()" style="width:130px">
                  <option value="" {{ (  $request->input('is_success') ==  '') ? 'selected' : '' }}> -- All result --</option>

                    @foreach ([ "success", "fail"] as $key => $value)
                      <option value="{{ $value }}" {{  (strlen($request->input('is_success') >0 ) &&  $value == $request->input('is_success')) ? 'selected' : '' }}>
                          {{ $value }}
                      </option>
                    @endforeach

                </select>
              </th>

              <th class="px-4 py-3">
                  {{ Form::number('amount' , $request->input('amount'), array('class' => 'form-control' , 'style'=>'width:110px' , 'placeholder' => "Amount" ,    'onchange'=>'this.form.submit()'  )) }}

                  @if ($request->input('sort_by') == '-amount' )
                    <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'amount']) }}"> &uarr; </a>
                  @elseif($request->input('sort_by') == 'amount' )
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-amount']) }}"> &darr;</a>
                    <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
                  @else
                      <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-amount']) }}"> &darr;</a>
                      <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'amount']) }}"> &uarr; </a>
                  @endif
              </th>

              <th class="px-4 py-3">
                  {{ Form::number('balance_after' , $request->input('balance_after'), array('class' => 'form-control' , 'style'=>'width:110px' , 'placeholder' => "Balance" ,  'onchange'=>'this.form.submit()'  )) }}

                  @if ($request->input('sort_by') == '-balance_after' )
                    <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'balance_after']) }}"> &uarr; </a>
                  @elseif($request->input('sort_by') == 'balance_after' )
                    <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-balance_after']) }}"> &darr;</a>
                    <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
                  @else
                      <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-balance_after']) }}"> &darr;</a>
                      <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'balance_after']) }}"> &uarr; </a>
                  @endif
              </th>


              <th class="px-4 py-3">
                 {{ Form::text('user' , $request->input('user'), array('class' => 'form-control' ,  'placeholder' => "User" , 'onchange'=>'this.form.submit()'  )) }}
              </th>

              <th class="px-4 py-3">
                <select class="form-control" name="operation_type" class="form-control" onchange="this.form.submit()" style="width:130px">
                  <option value="" {{ (  $request->input('operation_type') ==  '') ? 'selected' : '' }}> -- All type operation --</option>

                    @foreach ([ "debiting", "crediting"] as $key => $value)
                      <option value="{{ $value }}" {{  (strlen($request->input('operation_type') >0 ) &&  $value == $request->input('operation_type')) ? 'selected' : '' }}>
                          {{ $value }}
                      </option>
                    @endforeach

                </select>
              </th>

              <th class="px-4 py-3">
                 {{ Form::text('operation_user' , $request->input('operation_user'), array('class' => 'form-control' ,  'placeholder' => "Operation User" , 'onchange'=>'this.form.submit()'  )) }}
              </th>
              <th class="px-4 py-3"></th>
          </tr>
      </thead>
      <tbody>
        @foreach ($rows as $row)
          <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
              <td class="px-4 py-4">{{$row->id}}</td>
              <td class="px-4 py-4">{{$row->created_at}}</td>
              <td class="px-4 py-4">
                @if ($row->is_success === true)
                  <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded-full">Success</span>
                @else
                  <span class="bg-red-500 text-gray-200 text-xs px-2 py-1 rounded-full">Fail</span>
                @endif
              </td>
              <td class="px-4 py-4">{{$row->amount}} PW</td>
              <td class="px-4 py-4"> {{$row->balance_after}} PW</td>
              <td class="px-4 py-4"> {{$row->user_rel->name}}</td>
              <td class="px-4 py-4">


                @if ($row->operation_type === 'debiting')
                  {{$row->operation_type}}  &#8594;
                @else
                  &#8592;	 {{$row->operation_type}}
                @endif
              </td>
              <td class="px-4 py-4"> {{$row->operation_user_rel->name}}</td>
              <td class="px-4 py-4">
                <a href="{{ route('transaction.edit', $row->id)}}" class="bg-gray-600 text-gray-100 text-xs px-2 py-1 rounded-full">Edit</a>
                <a href="{{ route('transaction.show', $row->id)}}" class="bg-blue-600 text-gray-200 text-xs px-2 py-1 rounded-full">View</a>
              </td>
          </tr>
        @endforeach

      </tbody>
  </table>
{{ Form::close() }}

resources/views/admin_views/transaction/details.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                  <a href="{{route("transaction.edit",  $transaction->id)}}" class="bg-green-500 text-gray-100 rounded hover:bg-green-400 px-4 py-2 focus:outline-none">Edit Transaction</a>
                  <br>
                  <br>
                  <hr>

                  <div class="bg-white rounded-lg shadow-lg py-6">
                    <div class="block overflow-x-auto mx-6">
                        <table class="w-full text-left rounded-lg">
                            <tbody>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">ID Transaction</td>
                                    <td class="px-4 py-4">{{ $transaction->id }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">User</td>
                                    <td class="px-4 py-4"> <a href="{{route("user.show", $transaction->user_rel->id )}}"> {{ $transaction->user_rel->name }}  (id: {{ $transaction->user_rel->id }}) </a></td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Date\Time</td>
                                    <td class="px-4 py-4">{{ $transaction->created_at }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Amount</td>
                                    <td class="px-4 py-4">{{ $transaction->amount }} PW</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">type operation</td>
                                    <td class="px-4 py-4">{{ $transaction->operation_type }}</td>
                                </tr>

                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Operation User</td>
                                    <td class="px-4 py-4"> <a href="{{route("user.show", $transaction->operation_user_rel->id )}}"> {{$transaction->operation_user_rel->name}} (id: {{ $transaction->operation_user_rel->id }}) </a></td>
                                </tr>

                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Result</td>
                                    <td class="px-4 py-4">  @if ($transaction->is_success === true)
                                        <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded-full">Success</span>
                                      @else
                                        <span class="bg-red-500 text-gray-200 text-xs px-2 py-1 rounded-full">Fail</span>
                                      @endif
                                    </td>
                                </tr>
                                @if ($transaction->fail_message)
                                  <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                      <td class="px-4 py-4">Fail message</td>
                                      <td class="px-4 py-4">

                                          <span class="bg-red-500 text-gray-200 text-xs px-2 py-1 rounded-full">{{ $transaction->fail_message }}</span>

                                      </td>
                                  </tr>
                                @else

                                @endif




                            </tbody>
                        </table>
                    </div>
                  </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin_views/transaction/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                      <div class="bg-white rounded-lg shadow-lg py-6">
                        <div class="block overflow-x-auto mx-6">

                          @if ($errors->any())
                          <div class="bg-red-200 relative text-red-500 py-3 px-3 rounded-lg">
                              <ul>
                                  @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                  @endforeach
                              </ul>
                            </div>
                            <br>
                          @endif

                          <form method="post" action="{{route('transaction.update' , ["transaction"=>$transaction->id]) }}">
                            @method('PATCH')
                            @csrf

                              <label class="text-gray-600 font-light">Amount:</label>
                              {{ Form::text('amount', $transaction->amount, array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}

                              <label class="text-gray-600 font-light">Fail message:</label>
                              {{ Form::textarea('fail_message',  $transaction->fail_message   , array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' )) }}



                              <br>

                              {{Form::submit('Update',  array('class' => 'bg-green-500 text-gray-100 rounded hover:bg-green-400 px-4 py-2 focus:outline-none'))}}

                          </form>


                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin_views/transaction/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-9xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                      <h1 class="text-5xl font-normal leading-normal mt-0 mb-2 text-pink-800">Transactions</h1>

                      <div class="bg-white rounded-lg shadow-lg py-6">
                        <div class="block overflow-x-auto mx-6">


                            @include('admin_views.transaction._transaction_table')


                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>