routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
//

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//



Route::group(['middleware' => 'auth'], function(){

  Route::group(['middleware' => 'check_ban'], function(){
          // for users
        Route::get('/', 'App\Http\Controllers\TransactionController@transaction_history')->name("home");
        Route::get('/transaction/history', 'App\Http\Controllers\TransactionController@transaction_history')->name("transaction_history");
        Route::get('/transfer/create', 'App\Http\Controllers\TransactionController@transfer_create')->name("transfer_create");
        Route::get('/transfer/copy/{transaction_id}', 'App\Http\Controllers\TransactionController@transfer_copy')->name("transfer_copy");
        Route::post('/transfer/transfering', 'App\Http\Controllers\TransactionController@transfering')->name("transfering");
        Route::get('/transfer/result', 'App\Http\Controllers\TransactionController@transfer_result')->name("transfer_result");
        Route::get('/catalog/user-list', 'App\Http\Controllers\CatalogController@user_list')->name("user_list");
   });

  //admin control panel
  Route::group(['prefix' => 'admin'], function(){

        Route::group(['middleware' => 'can:isAdmin'], function(){
        //admin access
        Route::resource('user', 'App\Http\Controllers\AdminControllers\UserController');
        Route::resource('transaction', 'App\Http\Controllers\AdminControllers\TransactionController');

      });
  });
});


require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;


    public static $user_status = [
        0 => 'inactive',
        1 => 'active',
        2 => 'blocked',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function userdata__rel()
     {
        return $this->hasOne(UserData::class, 'user_id', 'id');
     }





    public static function get_roles_list()
     {
       return ["admin" , "user" , 'manager'];
     }


    public function is_banned()
     {
        $status = $this::$user_status[$this->status];
        if( $status == 'blocked') {
          return true;
        }
        return false;
     }

    public function get_status()
     {
        return $this::$user_status[$this->status];

     }



}

app/Http/Controllers/AdminControllers/UserController.php
<?php

namespace App\Http\Controllers\AdminControllers;

use \Validator;
use App\Http\Controllers\Controller;
use \Redirect;
use \Hash;
use Illuminate\Http\Request;

use App\Models\User;
use App\Helpers\Filters\UserFilter;

class UserController extends Controller
{


  // public function store(Request $request)
  // {
  //
  //    $request->flash();
  //
  //    $validator =  Validator::make($request->all(),[
  //      'name'=>'required',
  //      'email'=>'required|email',
  //      'status'=>'required|integer',
  //      'password'         => 'sometimes|required|min:6|max:14',
  //      'password_confirm' => 'required_with:password|same:password|min:6|max:14'
  //    ] );
  //
  //
  //    if ($validator->fails()) {
  //       return Redirect::to('user/create')
  //           ->withErrors($validator)
  //           ->withInput($request->input());
  //    }
  //
  //     $user = new User([
  //         'name' => $request->get('name'),
  //         'email' => $request->get('email'),
  //         'status' => (int) $request->get('status'),
  //         "password" => Hash::make($request->get('password')),
  //     ]);
  //
  //     $user->save();
  //     return redirect()->route('user.index', [])->with('success', 'User saved!');
  // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

       $users = UserFilter::get_rows($request);
       $roles = User::get_roles_list();
       $statuses = User::$user_status;
       return view('admin_views.user.index', compact('users' , 'request',  'roles', 'statuses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin_views.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function store(Request $request)
    // {
    //     //
    // }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $user = User::where(["id" => $id])->with("userdata__rel")->firstOrFail();
      return view('admin_views.user.profile', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
       $user = User::where(["id" => $id])->with("userdata__rel")->firstOrFail();

       $roles = User::get_roles_list();
       $statuses = User::$user_status;

       return view('admin_views.user.edit', compact('user', 'roles', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
          'name'=>'required|unique:users,name,'.$id,
          'email'=>'required|email|unique:users,email,'.$id,
          'status'=>'required|integer',
          'role'=>'required',
          'password' => 'sometimes|nullable|min:6|max:14',
          'password_confirm' => 'required_with:password|same:password|nullable|min:6|max:14'
        ]);


       $user = User::where(["id" => $id])->with("userdata__rel")->firstOrFail();
       $user->name =  $request->get('name');
       $user->email = $request->get('email');
       $user->status = $request->get('status');
       $user->role = $request->get('role');
       if(!empty($request->get('password'))) {
         $user->password = Hash::make($request->get('password'));
       }


       $user->save();
       return redirect()->route('user.index', [])->with('message', 'User updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     //
    //
    //     $contact = \App\Models\Contact::find($id);
    //     $contact->delete();
    //
    //     return redirect('/contact')->with('success', 'Contact deleted!');
    // }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin_views/user/_user_table.blade.php
<br>

{{ Form::open(array('url' => route('user.index') ,  'method' => 'get')) }}
  @csrf

  {{ $users->links() }}
  <br>
  <hr>
  <br>

  <table class="w-full text-left rounded-lg">
      <thead>
          <tr class="text-gray-800 border border-b-0">
              <th class="px-4 py-3">ID</th>
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">E-mail</th>
              <th class="px-4 py-3">Status</th>
              <th class="px-4 py-3">Role</th>
              <th class="px-4 py-3">Registration date</th>
              <th class="px-4 py-3">Actions</th>
          </tr>
      </thead>
      <thead>
        <tr class="text-gray-800 border border-b-0">
          <th class="px-4 py-3">
            {{ Form::number('id' , $request->input('id'), array('class' => 'form-control' , 'style'=>'width:80px' , 'placeholder' => "ID" , 'onchange'=>'this.form.submit()')) }}
            @if ($request->input('sort_by') == '-id' )
              <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
              <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'id']) }}"> &uarr; </a>
            @elseif($request->input('sort_by') == 'id' )
              <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-id']) }}"> &darr;</a>
              <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
            @else
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-id']) }}"> &darr;</a>
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'id']) }}"> &uarr; </a>
            @endif
          </th>
          <th class="px-4 py-3">
              {{ Form::text('name' , $request->input('name'), array('class' => 'form-control' ,  'style'=>'width:150px', 'placeholder' => "Name", 'onchange'=>'this.form.submit()')) }}
          </th>
          <th class="px-4 py-3">
               {{ Form::text('email' , $request->input('email'), array('class' => 'form-control' ,  'style'=>'width:150px',  'placeholder' => "E-mail " , 'onchange'=>'this.form.submit()')) }}
          </th>
          <th class="px-4 py-3">
            {{ Form::select('status', array_merge(['' => "-- all status --" ] , $statuses), $request->input('status') , array('class' => 'form-control' , 'onchange'=>'this.form.submit()' , 'style'=>'width:140px'))}}

            @if ($request->input('sort_by') == '-status' )
              <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
              <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'status']) }}"> &uarr; </a>
            @elseif($request->input('sort_by') == 'status' )
              <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-status']) }}"> &darr;</a>
              <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
            @else
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-status']) }}"> &darr;</a>
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'status']) }}"> &uarr; </a>
            @endif

          </th>
          <th class="px-4 py-3">
            {{ Form::select('role', array_combine(array_merge([ "" ] , $roles), array_merge([ "-- all roles --" ] , $roles)), $request->input('role') , array('class' => 'form-control' , 'onchange'=>'this.form.submit()' , 'style'=>'width:120px'))}}
          </th>
          <th class="px-4 py-3">
              Start date: {{ Form::date('date_start' , $request->input('date_start'), array('class' => 'form-control' , 'style'=>'width:150px' ,  'placeholder' => "Date start" , 'onchange'=>'this.form.submit()')) }}
              <br>
              End date: {{ Form::date('date_end' , $request->input('date_end'), array('class' => 'form-control', 'style'=>'width:150px' ,  'placeholder' => "Date end" , 'onchange'=>'this.form.submit()')) }}

              @if ($request->input('sort_by') == '-created_at' )
                <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded">&darr;</span>
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'created_at']) }}"> &uarr; </a>
              @elseif($request->input('sort_by') == 'created_at' )
                <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-created_at']) }}"> &darr;</a>
                <span class="bg-green-400 text-gray-100 text-xs px-2 py-1 rounded"> &uarr;</span>
              @else
                  <a href="{{ request()->fullUrlWithQuery(['sort_by' => '-created_at']) }}"> &darr;</a>
                  <a href="{{ request()->fullUrlWithQuery(['sort_by' => 'created_at']) }}"> &uarr; </a>
              @endif
          </th>
          <th class="px-4 py-3"></th>
        </tr>
      </thead>
      <tbody>
        @foreach($users as $user)
        <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
          <td class="px-4 py-4">{{$user->id}}</td>
          <td class="px-4 py-4">{{$user->name}}</td>
          <td class="px-4 py-4">{{$user->email}}</td>
          <td class="px-4 py-4">
            @switch( $user->get_status())
                @case("inactive")
                    <span style="color:orange">inactive</span>
                    @break

                @case("active")
                    <span style="color:green">active</span>
                    @break
                @case("blocked")
                    <span style="color:red">blocked</span>
                    @break
                @default
                    <span>{{$user->status}}</span>
            @endswitch
          </td>
          <td class="px-4 py-4">{{$user->role}}</td>
          <td class="px-4 py-4">{{ date('d.m.Y H:i:s', strtotime($user->created_at))}}</td>
          <td class="px-4 py-4">
            <a href="{{ route('user.edit', $user->id)}}" class="bg-gray-600 text-gray-100 text-xs px-2 py-1 rounded-full">Edit</a>
            <a href="{{ route('user.show', $user->id)}}" class="bg-blue-600 text-gray-200 text-xs px-2 py-1 rounded-full">View</a>

          </td>
        </tr>
        @endforeach

      </tbody>
    </table>



{{ Form::close() }}

resources/views/admin_views/user/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                      <div class="bg-white rounded-lg shadow-lg py-6">
                        <div class="block overflow-x-auto mx-6">

                          @if ($errors->any())
                            <div class="alert alert-danger">
                              <ul>
                                  @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                  @endforeach
                              </ul>
                            </div>
                            <br>
                          @endif

                          <form method="post" action="{{route('user.store') }}">
                              @csrf

                              <label class="text-gray-600 font-light">E-mail:</label>
                              {{ Form::text('email', old('email'), array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}


                              <label class="text-gray-600 font-light">Name:</label>
                              {{ Form::text('name', old('name'), array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}

                              <label class="text-gray-600 font-light">Status:</label>
                              {{ Form::text('status', old('status'), array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}


                              <label class="text-gray-600 font-light">Password:</label>
                              {{ Form::text('password', old('password'), array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}

                              <label class="text-gray-600 font-light">Password Confirm:</label>
                              {{ Form::text('password_confirm', old('password_confirm'), array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}


                              {{Form::submit('Add User',  array('class' => 'bg-green-500 text-gray-100 rounded hover:bg-green-400 px-4 py-2 focus:outline-none'))}}

                          </form>


                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin_views/user/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                      <div class="bg-white rounded-lg shadow-lg py-6">
                        <div class="block overflow-x-auto mx-6">

                          @if ($errors->any())
                          <div class="bg-red-200 relative text-red-500 py-3 px-3 rounded-lg">
                              <ul>
                                  @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                  @endforeach
                              </ul>
                            </div>
                            <br>
                          @endif

                          <form method="post" action="{{route('user.update' , ["user"=>$user->id]) }}">
                            @method('PATCH')
                            @csrf

                              <label class="text-gray-600 font-light">E-mail:</label>
                              {{ Form::text('email', $user->email, array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}


                              <label class="text-gray-600 font-light">Name:</label>
                              {{ Form::text('name',  $user->name   , array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}

                              <label class="text-gray-600 font-light">Status:</label>
                              {{Form::select('status', $statuses,  $user->status , array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500',  "required" => "required"  )) }}


                              <label class="text-gray-600 font-light">Role:</label>
                              <div class="flex">
                                @foreach ($roles as $role)
                                  <div class="flex items-center mb-2 mr-4">
                                      {!! Form::radio('role', $role , isset( $user->role) ? $user->role === $role : false,   array('class' => 'h-4 w-4 text-gray-700 px-3 py-3 border rounded mr-2')) !!}
                                      <label for="radio-example-1" class="text-gray-600">{{$role}}</label>
                                  </div>

                                @endforeach
                              </div>


                              <label class="text-gray-600 font-light">Password:</label>
                              {{Form::password('password',   array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' )) }}


                              <label class="text-gray-600 font-light">Confirm password:</label>
                              {{Form::password('password_confirm',  array('class' => 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' )) }}


                              <br>

                              {{Form::submit('Update',  array('class' => 'bg-green-500 text-gray-100 rounded hover:bg-green-400 px-4 py-2 focus:outline-none'))}}

                          </form>


                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin_views/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-9xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                      <h1 class="text-5xl font-normal leading-normal mt-0 mb-2 text-pink-800">Users</h1>

                      <div class="bg-white rounded-lg shadow-lg py-6">
                        <div class="block overflow-x-auto mx-6">


                            @include('admin_views.user._user_table')


                        </div>
                      </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin_views/user/profile.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>



    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                  <a href="{{route("user.edit",  $user->id)}}" class="bg-green-500 text-gray-100 rounded hover:bg-green-400 px-4 py-2 focus:outline-none">Edit User</a>
                  <br>
                  <br>
                  <hr>

                  <div class="bg-white rounded-lg shadow-lg py-6">
                    <div class="block overflow-x-auto mx-6">
                        <table class="w-full text-left rounded-lg">
                            <tbody>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">ID user</td>
                                    <td class="px-4 py-4">{{ $user->id }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Name</td>
                                    <td class="px-4 py-4">{{ $user->name }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">E-Mail</td>
                                    <td class="px-4 py-4">{{ $user->email }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Role</td>
                                    <td class="px-4 py-4">{{ $user->role }}</td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Status</td>
                                    <td class="px-4 py-4">

                                      @switch( $user->get_status())
                                          @case("inactive")
                                              <span style="color:orange">inactive</span>
                                              @break

                                          @case("active")
                                              <span style="color:green">active</span>
                                              @break
                                          @case("blocked")
                                              <span style="color:red">blocked</span>
                                              @break
                                          @default
                                              <span>{{$user->status}}</span>
                                      @endswitch

                                    </td>
                                </tr>
                                <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
                                    <td class="px-4 py-4">Balance</td>
                                    <td class="px-4 py-4">

                                      @if(empty( $user->userdata__rel))
                                             NULL
                                          @else
                                            {{$user->userdata__rel->current_balance}} PW
                                          @endif

                                    </td>
                                </tr>


                            </tbody>
                        </table>
                    </div>
                  </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>